workspace = { members = ["entity", "migration", "msg"] }
[package]
name = "chat-server"
version = "0.1.1"
edition = "2024"
description = "A Simple Chat Server"
authors = ["quyc <quycsff@gmail.com>"]
repository = "https://github.com/quyc07/chat-server"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
entity = { path = "entity", version = "0.1.0" }
migration = { path = "migration", version = "0.1.0" }
msg = { path = "msg", version = "0.1.0" }
axum = { version = "0.8.1", features = ["macros"] }
axum-extra = { version = "0.10.0", features = ["typed-header"] }
jsonwebtoken = "9"
jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.8"
validator = { version = "0.20.0", features = ["derive"] }
thiserror = "2.0.12"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
serde_html_form = "0.2.4"
tokio = { version = "1.35.1", features = ["full"] }
tokio-stream = "0.1.14"
futures = "0.3.30"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "local-time"] }
tracing-appender = "0.2.3"
tower-http = { version = "0.6.2", features = ["fs"] }
color-eyre = "0.6"
chrono = "0.4.31"
sea-orm = { version = "1.0.0", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros", "debug-print"] }
itertools = "0.14.0"
utoipa = { version = "5.3.1", features = ["axum_extras", "chrono"] }
utoipa-swagger-ui = { version = "9.0.0", features = ["axum"] }
moka = { version = "0.12.8", features = ["future"] }
openssl = { version = "0.10", features = ["vendored"] }