services:
  dgraph:
    # docker run -it -p 8080:8080 -p 9080:9080 -v ~/dgraph:/dgraph dgraph/standalone:latest
    image: dgraph/dgraph:latest
    container_name: dgraph
    ports:
      - "8080:8080"
      - "9080:9080"
    volumes:
      - ./volume/dgraph:/graph
  chat-server:
    image: chat-server:1.0
    container_name: chat-server
    ports:
      - "3000:3000"