version: '3'
services:
  dgraph:
    # docker run -it -p 8080:8080 -p 9080:9080 -v ~/dgraph:/dgraph dgraph/standalone:latest
    image: dgraph/standalone:latest
    container_name: dgraph
    ports:
      - "8080:8080"
      - "9080:9080"
    volumes:
      - ~/volume/dgraph:/graph
