version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - D:\volume\mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Aa123456
      TZ: Asia/Shanghai
