version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - D:\volume\mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Aa123456
      TZ: Asia/Shanghai
  nginx:
    image: nginx:latest
    container_name: web
    ports:
      - 80:80
      - 443:443
    volumes:
      - D:\volume\nginx\nginx.conf:/etc/nginx/nginx.conf
      - D:\https:/opt/nginx/ssl_key
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    ports:
      - 443:443
    volumes:
      - D:\volume\onlyoffice:/var/www/onlyoffice/Data
    environment:
      JWT_SECRET: abc123
