//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

pub mod prelude;

pub mod user;

pub fn add(left: usize, right: usize) -> usize {
    left + right
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        let result = add(2, 2);
        assert_eq!(result, 4);
    }
}
