//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.11

pub mod prelude;

pub mod sea_orm_active_enums;
pub mod user;
pub mod group;
pub mod user_group_rel;

pub mod friend_request;
pub mod read_index;