//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub use super::friend_request::Entity as FriendRequest;
pub use super::group::Entity as Group;
pub use super::user::Entity as User;
pub use super::user_group_rel::Entity as UserGroupRel;
